Fixed: Build failure because mamuesp/common-tools has been moved.
The mos.yml file for `timezones` specifies the dependencies as such:

```yml
libs:
  - origin: https://github.com/mamuesp/common-tools
  - origin: https://github.com/mamuesp/zip-tools
```

However, the build fails because `common-tools` has been moved to a different Github account:

> common-tools: Does not exist, cloning from "https://github.com/mamuesp/common-tools"...
> Error: exit status 128
> /private/tmp/mos-20190426-57195-kki69o/mos-tool-2034cc00c37fee33b300b1c5869b8eeff328fdfa/src/cesanta.com/common/go/ourgit/ourgit_shell.go:197: cloning https://github.com/mamuesp/common-tools: Cloning into '/Users/sfree/Development/mongoose/lightstrip-app/deps/common-tools'...
> fatal: could not read Username for 'https://github.com': Device not configured

The fix is to replace the library URL.